### ISSUE TITLE
https://cssplice.org not forwarding properly to https://cssplice.github.io

### ISSUE THREAD

**Issue by cashaffer** [CSSPLICE/CSSPLICE.github.io#52]
Something is wrong with the GoDaddy setup for managing the domain. http://cssplice.org works fine. But https://cssplice.org is not forwarding correctly.

**Comment by bedmison** [comment]
This is sorted. TLDR version is that godaddy only allows on protocol forward per DNS name. So we could have http or https but not both.

Updated the site using the GitHub-preferred setup (https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)
with an assist from https://hackernoon.com/how-to-set-up-godaddy-domain-with-github-pages-a9300366c7b
